sudo: false
language: ruby
cache:
  directories:
    - node_modules
notifications:
  email: false
rvm:
  - '2.4.1'
after_success:
  - bundle exec rake gem:release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
